services:
  - name: frontend
    type: web
    env: static
    staticPublishPath: frontend/build
    buildCommand: cd frontend && npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - name: backend
    type: web
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
